<script lang="ts">
  /**
   * On-page view of what an agent can do here, and what it has done.
   *
   * Mirrors the affordance the WebMCP shopping demo established: a page that
   * exposes agent tools should say so on the page itself, not only in browser
   * chrome the user has to go looking for. Observation only — nothing here can
   * grant, revoke or invoke anything.
   */
  import { onMount } from 'svelte'
  import * as pageTools from '../../lib/browser-tools/page-controller'
  import * as activity from '../../lib/browser-tools/activity-log'
  import type { ActivityEntry } from '../../lib/browser-tools/activity-log'
  import type { ToolDescriptor } from '../../lib/browser-tools/contract'

  let { onClose }: { onClose: () => void } = $props()

  let published = $state<ToolDescriptor[]>([])
  let enabled = $state(false)
  let entries = $state<ActivityEntry[]>([])
  let open = $state(false)

  /**
   * A page nobody enabled still computes a tool set, but no agent can reach
   * it. Reporting those as available would be the one lie this panel exists
   * to prevent, so an unenabled page has no tools as far as it is concerned.
   */
  const tools = $derived(enabled ? published : [])
  const siteTools = $derived(tools.filter((t) => t.source.kind === 'native'))
  const janusTools = $derived(tools.filter((t) => t.source.kind !== 'native'))

  onMount(() => {
    const stopTools = pageTools.subscribeTools((next, isEnabled) => {
      published = [...next].sort((a, b) => a.name.localeCompare(b.name))
      enabled = isEnabled
    })
    const stopActivity = activity.subscribe((next) => { entries = next })
    void pageTools.publish()
    return () => { stopTools(); stopActivity() }
  })

  function clockTime(at: number): string {
    return new Date(at).toLocaleTimeString([], { hour12: false })
  }

  function args(input: Record<string, unknown>): string {
    try {
      return JSON.stringify(input)
    } catch {
      return '{…}'
    }
  }

  function took(entry: ActivityEntry): string {
    if (entry.endedAt === undefined) return ''
    return `${entry.endedAt - entry.startedAt}ms`
  }
</script>

<div class="janus-agent-tools">
  {#if open}
    <div class="panel" role="dialog" aria-label="Agent tools">
      <div class="head">
        <span class="title">Agent tools</span>
        <span class="count">{tools.length}</span>
        <button class="icon" onclick={() => (open = false)} aria-label="Collapse">&minus;</button>
        <button class="icon" onclick={onClose} aria-label="Hide panel">&times;</button>
      </div>

      <div class="body">
        {#if !enabled}
          <p class="empty">
            This page is not enabled, so no agent can reach it. Turn it on from
            the Janus popup.
          </p>
        {:else if !tools.length}
          <p class="empty">No tools are published on this page.</p>
        {/if}

        {#if siteTools.length}
          <p class="section">Provided by this site</p>
          {#each siteTools as tool (tool.toolId)}
            <div class="tool">
              <span class="name">{tool.name}</span>
              {#if tool.readOnlyHint}<span class="tag">read-only</span>{/if}
            </div>
          {/each}
        {/if}

        {#if janusTools.length}
          <p class="section">Generated by Janus</p>
          {#each janusTools as tool (tool.toolId)}
            <div class="tool">
              <span class="name">{tool.name}</span>
              {#if tool.readOnlyHint}<span class="tag">read-only</span>{/if}
              {#if tool.consequentialHint}<span class="tag warn">writes</span>{/if}
            </div>
          {/each}
        {/if}

        <p class="section">Activity</p>
        {#if !entries.length}
          <p class="empty">Tool calls run by Janus show up here.</p>
        {:else}
          {#each entries as entry (entry.id)}
            <div class="entry" class:failed={entry.status === 'error'}>
              <div class="entry-head">
                <span class="name">{entry.name}</span>
                <span class="time">{clockTime(entry.startedAt)}</span>
                {#if entry.caller === 'webmcp'}<span class="tag">page agent</span>{/if}
                {#if entry.status === 'error'}
                  <span class="tag bad">error</span>
                {:else if entry.status === 'running'}
                  <span class="tag live">running</span>
                {:else}
                  <span class="time">{took(entry)}</span>
                {/if}
              </div>
              <div class="mono dim">{args(entry.input)}</div>
              {#if entry.summary}<div class="mono dim">{entry.summary}</div>{/if}
            </div>
          {/each}
        {/if}

        <p class="foot">
          Shows calls Janus runs. Tools the site registers itself may also be
          called by the site's own agent without appearing here.
        </p>
      </div>
    </div>
  {:else}
    <button class="pill" onclick={() => (open = true)}>
      Agent tools
      <span class="count">{tools.length}</span>
    </button>
  {/if}
</div>

<style>
  .janus-agent-tools {
    position: fixed;
    right: 16px;
    bottom: 16px;
    z-index: 2147483646;
    font-family: system-ui, -apple-system, sans-serif;
    font-size: 12px;
    line-height: 1.45;
    color: #1a1a1a;
    text-align: left;
    direction: ltr;
  }
  .pill {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 14px;
    border: 1px solid #e2e2e2;
    border-radius: 999px;
    background: #fff;
    box-shadow: 0 6px 24px rgba(0, 0, 0, 0.12);
    font: inherit;
    font-weight: 600;
    color: inherit;
    cursor: pointer;
  }
  .panel {
    width: 380px;
    max-height: min(520px, 70vh);
    display: flex;
    flex-direction: column;
    border: 1px solid #e2e2e2;
    border-radius: 12px;
    background: #fff;
    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.16);
    overflow: hidden;
  }
  .head {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 12px 14px;
    border-bottom: 1px solid #f0f0f0;
  }
  .title { font-weight: 700; }
  .count {
    padding: 1px 8px;
    border-radius: 999px;
    background: #1f7a4d;
    color: #fff;
    font-size: 11px;
    font-weight: 600;
  }
  .icon {
    margin-left: auto;
    border: 0;
    background: none;
    color: #999;
    font-size: 15px;
    line-height: 1;
    padding: 2px 4px;
    cursor: pointer;
  }
  .icon + .icon { margin-left: 0; }
  .icon:hover { color: #333; }
  .body { overflow-y: auto; padding: 4px 14px 14px; }
  .section {
    margin: 14px 0 6px;
    font-size: 10px;
    font-weight: 600;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: #999;
  }
  .tool {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 2px 0;
  }
  .name {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 11.5px;
  }
  .tag {
    margin-left: auto;
    padding: 1px 7px;
    border-radius: 999px;
    background: #f0f0f0;
    color: #666;
    font-size: 10px;
    white-space: nowrap;
  }
  .tag + .tag { margin-left: 0; }
  .tag.warn { background: #fdf0e3; color: #a85f16; }
  .tag.bad { background: #fde7e9; color: #b3261e; }
  .tag.live { background: #e7f0fd; color: #1a56b3; }
  .entry {
    margin-bottom: 6px;
    padding: 8px 10px;
    border-radius: 8px;
    background: #f7f7f7;
  }
  .entry.failed { background: #fdf2f3; }
  .entry-head { display: flex; align-items: center; gap: 8px; }
  .time { color: #999; font-size: 10.5px; }
  .entry-head .time:first-of-type { margin-right: auto; }
  .mono {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 11px;
    overflow-wrap: anywhere;
  }
  .dim { color: #666; margin-top: 3px; }
  .empty { margin: 4px 0; color: #999; }
  .foot {
    margin: 14px 0 0;
    padding-top: 10px;
    border-top: 1px solid #f0f0f0;
    font-size: 10.5px;
    color: #aaa;
  }
</style>
