/**
 * The on-page agent tools panel renders from the real built extension.
 *
 * No daemon and no pairing: the panel is a display preference over whatever
 * the page controller has published, so it must stand up on its own. That is
 * also the weakest case worth asserting — if it only worked once a daemon was
 * attached, a user toggling it on an ordinary tab would see nothing and have
 * no way to tell the panel from a broken build.
 */

import { test, expect } from '@playwright/test'
import {
  enablePageThroughUi, launchExtension, pairThroughUi, type ExtensionHandle,
} from './fixtures/extension'
import { startDaemon, type DaemonHandle } from './fixtures/daemon'
import { startSite, type SiteHandle } from './fixtures/site'
import { connectMcp, type McpHandle } from './fixtures/mcp'

let ext: ExtensionHandle
let daemon: DaemonHandle
let site: SiteHandle
let pairingId: string
const clients: McpHandle[] = []

test.beforeAll(async () => {
  daemon = await startDaemon()
  site = await startSite()
  ext = await launchExtension()

  const settings = await ext.settings()
  ;({ pairingId } = await pairThroughUi(settings, daemon.mcpUrl))
  await settings.close()
})

test.afterAll(async () => {
  for (const client of clients) await client.close().catch(() => {})
  await ext?.stop()
  await site?.stop()
  await daemon?.stop()
})

async function agent(label: string): Promise<McpHandle> {
  const handle = await connectMcp(daemon.mcpUrl, await daemon.createClient(pairingId, label))
  clients.push(handle)
  return handle
}

test('the panel appears when the preference is on and reports the tool set', async () => {
  const page = await ext.context.newPage()
  await page.goto('https://example.com/')

  const panel = page.locator('#janus-agent-tools-root')
  await expect(panel).toHaveCount(0)

  // Set the preference the way the popup does, through extension storage.
  const [worker] = ext.context.serviceWorkers()
  await worker.evaluate(() => chrome.storage.local.set({ janus_tools_overlay: true }))

  await expect(panel).toHaveCount(1)
  const pill = panel.getByRole('button', { name: /Agent tools/ })
  await expect(pill).toBeVisible()
  await expect(pill).toHaveText(/0/)

  // Expanding replaces the pill with the panel, so the count is asserted first.
  await pill.click()
  await expect(panel.getByText('Activity')).toBeVisible()
  // `publish()` computes a tool set on any page, enabled or not. Reporting
  // those as available on a page no agent can reach is the specific failure
  // this asserts against.
  await expect(panel.getByText(/This page is not enabled/)).toBeVisible()

  await page.screenshot({ path: 'test-results/agent-tools-overlay.png' })

  // Turning the preference off withdraws it without a navigation.
  await worker.evaluate(() => chrome.storage.local.set({ janus_tools_overlay: false }))
  await expect(panel).toHaveCount(0)
  await page.close()
})

test('an enabled page lists its tools and records the calls an agent makes', async () => {
  const page = await ext.context.newPage()
  await page.goto(site.url)

  const popup = await ext.popup()
  await enablePageThroughUi(popup)
  await popup.close()

  const [worker] = ext.context.serviceWorkers()
  await worker.evaluate(() => chrome.storage.local.set({ janus_tools_overlay: true }))

  const panel = page.locator('#janus-agent-tools-root')
  await panel.getByRole('button', { name: /Agent tools/ }).click()
  await expect(panel.getByText('Generated by Janus')).toBeVisible()
  await expect(panel.getByText('read_page', { exact: true })).toBeVisible()

  // Before any call, the activity section has to be honest about being empty.
  await expect(panel.getByText(/Tool calls run by Janus show up here/)).toBeVisible()

  const client = await agent('overlay')
  const pages = JSON.parse((await client.call('list_pages', {})).text) as Array<{ pageId: string }>
  const listed = JSON.parse(
    (await client.call('list_page_tools', { pageId: pages[0].pageId })).text,
  ) as { tools: Array<{ name: string; toolId: string; revision: number }> }
  const readPage = listed.tools.find((t) => t.name === 'read_page')!

  // Asserted, not fire-and-forget: a rejected call never reaches the page, so
  // an empty activity list would otherwise look like a panel bug.
  const result = await client.call('call_page_tool', {
    pageId: pages[0].pageId, toolId: readPage.toolId, revision: readPage.revision, input: {},
  })
  expect(result.isError, result.text).toBe(false)
  // The panel is in the DOM but it is not the page. Reading it back as content
  // would feed the agent its own tool list and waste the text budget.
  expect(result.text).toContain('Fixture shop')
  expect(result.text).not.toContain('Generated by Janus')

  // The call arrived over MCP, so the panel is reporting work it did not
  // itself initiate — which is the whole point of showing it on the page.
  const entry = panel.locator('.entry').first()
  await expect(entry).toContainText('read_page')
  await expect(entry).not.toContainText('error')

  await page.screenshot({ path: 'test-results/agent-tools-overlay-active.png' })
})
